55 checkpoints challenge
Miro-Ali-Akbar/DSP-Fikon pull request #58
Opened 2024-05-02 13:55 UTC by TROCADER

Geofences are placed evenly based on distance. Easy to change both number of geofences (checkpoints) and minimum distance between them. If the distance is not good enough it will check against the next upcoming point instead.

2024-05-02 14:02 UTC, TROCADER commented
Based on #54 . Merging this should merge the other (I think, no promises).

2024-05-03 08:01 UTC, tubj5452 requested changes
merge conflicts

2024-05-03 08:01 UTC, tubj5452 commented on client/lib/pages/generated_map_page.dart
> +  // if (!inIntervall) {
tillbaka?

2024-05-03 08:01 UTC, tubj5452 commented on client/lib/pages/generated_map_page.dart
> +  // Circle
Är det fortf. en circle?

2024-05-03 08:15 UTC, TROCADER commented on client/lib/pages/generated_map_page.dart
> +  // if (!inIntervall) {
Fixat

2024-05-03 08:17 UTC, TROCADER commented on client/lib/pages/generated_map_page.dart
> +  // if (!inIntervall) {
Återställde till din version av filen

2024-05-03 08:17 UTC, TROCADER commented on client/lib/pages/generated_map_page.dart
> +  // Circle
Återställde till din version av filen

2024-05-03 08:54 UTC, merged